### ISSUE TITLE
Issue with the Getting Started page git command for Linux installation

### ISSUE THREAD

**Issue by PannierResearchLab** [idaholab/malamute#177]
## Bug Description
I'm posting this here because I don't know who maintains the MALAMUTE getting started webpage.
On this page: https://mooseframework.inl.gov/malamute/getting_started/installation.html
there is an instruction with this line: git clone git@github.com:idaholab/malamute.git
It did not work for me.
However, this did work: git clone https://www.github.com/iaholab/malamute
I suggest updating the website with the line that worked.

## Steps to Reproduce
Start installing MALAMUTE per the instructions on that webpage on a Ubuntu 22 LTS installation and you may also get stuck at that git command not working

I have not tested this on other machines

## Impact
Annoyance, especially for new users

**Comment by cticenhour** [comment]
Thanks for the feedback. The instructions make an assumption that you have an SSH public key registered to your GitHub account, since GitHub hasn't allowed HTTPS `git push` for some time (without a Personal Access Token, that is). However, as you discovered, there isn't any restriction on HTTPS `git clone` to local machines. I'm glad you found a workaround.

I will make an adjustment to the getting started instructions to reflect this option!
