### ISSUE TITLE
MALAMUTE needs example/demonstration and getting started documentation

### ISSUE THREAD

**Issue by moosebuild** [idaholab/malamute#7]
In [GitLab](https://hpcgitlab.hpc.inl.gov/idaholab/malamute/-/issues/7) by @cticenhour on Oct 12, 2021, 11:27

## Reason
Currently, placeholders are in place for examples/demonstration problems and the getting started page. These need to be added so that new users can better navigate the capability available to them. 

## Design

- Replace `doc/content/demonstration/Placeholder.md` with summary documents for the current MALAMUTE examples.
- Replace `doc/content/getting_started/Placeholder.md` with getting started instructions
- Add links to both from the home page and/or navigation. 

## Impact
Make MALAMUTE easier to use for new users

**Comment by moosebuild** [comment]
In GitLab by @cticenhour on Oct 12, 2021, 11:34

@jiangwen84 Could you add some documentation for the melt pool examples from Valhalla when you get some time? I am happy to write up some getting started instructions.

**Comment by moosebuild** [comment]
In GitLab by @jiangwen84 on Oct 12, 2021, 11:39

@cticenhour Sure! I will work on it.

**Comment by moosebuild** [comment]
In GitLab by @cticenhour on Oct 20, 2021, 13:59

mentioned in commit 78c9ed43d54fba077b1665a5789d153c918b1a1b

**Comment by cticenhour** [comment]
- `doc/content/getting_started/Placeholder.md` was replaced in commit 78c9ed4.
- `doc/content/demonstration/Placeholder.md` will be replaced in #124

Contrary to what was said in 2021, additions of any future examples in the demonstration landing page should be added under their own issues rather than referencing this one. This should be closed with #124.
